### ISSUE TITLE
We should probably choose a license to put this under.

### ISSUE THREAD

**Issue by auxiliary-character** [DenfeldRobotics4009/2015_Lopez_Jr#7]

**Comment by nikolojedison** [comment]
Any suggestions?

**Comment by auxiliary-character** [comment]
[WPILib and RobotPy](https://github.com/robotpy/robotpy-wpilib/blob/master/wpilib/LICENSE.txt) are licensed under the 3-clause BSD license.

**Comment by nikolojedison** [comment]
Just at a cursory glance, it looks fine. I'll look further into it later.

**Comment by nikolojedison** [comment]
3-clause BSD license has been added.

**Comment by auxiliary-character** [comment]
Wait, is "DNA Robotics" an official legal entity? RobotPy had to copyright it under the devs' names. This might be worth asking Andy about.

**Comment by nikolojedison** [comment]
Official legal name has been added: Denfeld DNA FIRST Robotics Team 4009
